/**
 * Configurações básica
 *
 * @type {{protocol: (string|null), defaultMethod: string, status: string}}
 */
export default {
	status: process.env.NODE_ENV,
	protocol: document ? document.location.protocol : null,
	// analyticUrl: "http://api.oston.io/oi-go/v1/interactions/",
	analyticUrl: "https://eng53nosqyte9.x.pipedream.net/",
	referer: "",
	landing: "",
	pin: "",
	plans: [
		[
			{
				name: "Oi Mais Controle Básico",
				code: "OCSF155",
				class: "BASICO",
				payment_type: "credit_card",
				price: "39.99",
				data_in_gb: 4,
				data_bonus_in_gb: 0,
				apps: "WhatsApp,Messenger",
				summary_file: "sumario-oimaiscontrole-cartao-basico_as.pdf",
				rule_file: "ta-oimaiscontrole-cartao-as.pdf",
			},
			{
				name: "Oi Mais Controle Básico",
				code: "OCSF116",
				class: "BASICO",
				payment_type: "boleto",
				price: "44.99",
				data_in_gb: 4,
				data_bonus_in_gb: 0,
				apps: "WhatsApp,Messenger",
				summary_file: "sumario-oimaiscontrole-boleto-basico-as.pdf",
				rule_file: "ta-oimaiscontrole-boleto-as.pdf",
			},
		],
		[
			{
				name: "Oi Mais Controle Intermediário",
				code: "OCSF171",
				class: "INTERMEDIÁRIO",
				payment_type: "credit_card",
				price: "49.99",
				data_in_gb: 12,
				data_bonus_in_gb: 4,
				apps: "WhatsApp,Messenger,Facebook,Instagram",
				summary_file: "sumario-oimaiscontrole-cartao-basico_as.pdf",
				rule_file: "ta-oimaiscontrole-cartao-as.pdf",
			},
			{
				name: "Oi Mais Controle Intermediário",
				code: "OCSF138",
				class: "INTERMEDIÁRIO",
				payment_type: "boleto",
				price: "54.99",
				data_in_gb: 12,
				data_bonus_in_gb: 0,
				apps: "WhatsApp,Messenger,Facebook",
				summary_file: "sumario-oimaiscontrole-boleto-basico-as.pdf",
				rule_file: "ta-oimaiscontrole-boleto-as.pdf",
			},
		],
		[
			{
				name: "Oi Mais Controle Avançado",
				code: "OCSF159",
				class: "AVANÇADO",
				payment_type: "credit_card",
				price: "99.9",
				data_in_gb: 50,
				data_bonus_in_gb: 0,
				apps: "WhatsApp,Messenger,Facebook,Instagram,Youtube,Netflix",
				summary_file: "sumario-oimaiscontrole-cartao-basico_as.pdf",
				rule_file: "ta-oimaiscontrole-cartao-as.pdf",
			},
			{
				name: "Oi Mais Controle Avançado",
				code: "OCSF150",
				class: "AVANÇADO",
				payment_type: "boleto",
				price: "99.9",
				data_in_gb: 50,
				data_bonus_in_gb: 0,
				apps: "WhatsApp,Messenger,Facebook,Instagram,Youtube,Netflix",
				summary_file: "sumario-oimaiscontrole-boleto-basico-as.pdf",
				rule_file: "ta-oimaiscontrole-boleto-as.pdf",
			},
		],
		[
			{
				name: "Oi Mais Controle Top",
				code: "OCSF172",
				class: "TOP",
				payment_type: "credit_card",
				price: "129.9",
				data_in_gb: 100,
				data_bonus_in_gb: 0,
				apps: "WhatsApp,Messenger,Facebook,Instagram,Youtube,Netflix",
				summary_file: "sumario-oimaiscontrole-cartao-basico_as.pdf",
				rule_file: "ta-oimaiscontrole-cartao-as.pdf",
			},
			{
				name: "Oi Mais Controle Top",
				code: "OCSF173",
				class: "TOP",
				payment_type: "boleto",
				price: "129.9",
				data_in_gb: 100,
				data_bonus_in_gb: 0,
				apps: "WhatsApp,Messenger,Facebook,Instagram,Youtube,Netflix",
				summary_file: "sumario-oimaiscontrole-boleto-basico-as.pdf",
				rule_file: "ta-oimaiscontrole-boleto-as.pdf",
			},
		],
	],
	cards: [],
	card: {},
	url: {
		site:
			document.location.origin +
			document.location.pathname.replace("index.html", ""),
		header: "http://clic.news/headers/",
		state: "https://api.gateway.oston.io/oi-ofertas/v1/sales/states",
		ddd:
			"https://api.gateway.oston.io/oi-ofertas/v1/sales/area_codes?state=",
	},
	birthday: {
		day: "00",
		month: "00",
		year: "0000",
	},
	user: {},
	states: [],
	ddds: [],
	state: "",
	ddd: "",
};
